### PR TITLE
Closes #23: Add tests to increase coverage of 3.17

### LINKED ISSUE #23: Add tests to increase coverage of 3.17
**Context**
Probably to do after #25 as it will deeply change the LRC logic on the beacon.

#7 has been implemented but there are no tests, making the CI on the PR fail for lack of test coverage, and introduction of code issues (code smells).
While the new beacon script itself has been added from #7 into WP Rocket 3.17 feature branch, allowing to test, it would be good to clean-up the rocket-script repository and add code coverage, and look at the code issues.

**Expected behavior**
Build on top of #20 to make the CI pass:
- Increase code coverage
- Look into the code issues and maybe fix them

**Acceptance Criteria**
#20 CI passes.
We should not need QA on this, unless the code itself is changed.

### PR DESCRIPTION
**Pull request by jeawhanlee**
# Description

Fixes #23 
Add tests for the LRC beacon to increase coverage.

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).
- [x] Sub-task of #7 

## Detailed scenario

N/A

### Documentation

Add unit tests for LRC beacon

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Comment by MathieuLamiot** [comment]
Thanks for the first tests @jeawhanlee 🙏 
Would it make sense to also test some of the private methods? Not all of them are relevant for testing, but some contain core logic that could be good to capture in tests?

See the coverage report for more details: https://app.codacy.com/gh/wp-media/rocket-scripts/coverage/files/123936609510

**Comment by MathieuLamiot** [comment]
@wp-media/engineering-plugin-team Since @jeawhanlee is off today, I am bringing this back to ToDo so that someone can pick it up and consider the above comment: should we cover some of the private methods too? And if yes, add some coverage to the relevant methods.

**Comment by wordpressfan** [comment]
I believe we can add small direct tests for those mentioned methods like `_getElementDistance` and others to increase the coverage here, and this is quick to tackle.

**Comment by wordpressfan** [comment]
That PR is taking more than expected with me because the current PR tests depending on mocking the methods using prototypes so no way to test those methods that way because if we mocked a method in one test, we can't remove this mock in the next test to validate the base method code.
That's why I'm moving from that to use Sinon Stubs.

**Review by MathieuLamiot — APPROVED** [review]

**Pull request merged**
